### PR TITLE
Ft social logins 159356731

### PR DESCRIPTION
**Pull request by brandeddavid**
#### What does this PR do?
Enables social logins - Facebook, GitHub, Google

##### Currently:
Login via form only.

##### Expected:
In addition to the login form, the user can also user their Facebook, GitHub or Google accounts to login.

#### How should this be manually tested?
Navigate to the  login page. Choose the social account you want to login with. Authorize account and voila, you are logged in.

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/159356731

##### Log in Page:
screen shot 2018-08-09 at 9 29 56 am

##### Log in via Google:
screen shot 2018-08-09 at 9 16 32 am

##### Log in via Facebook:
screen shot 2018-08-09 at 9 36 24 am

##### Log in via GitHub:
screen shot 2018-08-09 at 9 35 39 am

### CODE REVIEW

**Comment by Nerldy** [comment]
Good job. Only thing I could add is that the social media login buttons seem a bit crowded and I think adding some text next to the buttons can also minimize confusion as not all users can understand the icons. You could separate them and make the login page look something like the photo below

image

**Comment by brandeddavid** [comment]
Valid point @Nerldy working on it. Thanks.

**Comment by brandeddavid** [comment]
@Nerldy Updated
screen shot 2018-08-10 at 11 09 03 am

**Comment by Nerldy** [comment]
Much better

**Pull request merged**
