### PR TITLE
[FT #159356710] Fix pep8 errors and warnings

### PR DESCRIPTION
**Pull request by brandeddavid**
#### What does this PR do?
This PR fixes pep8 errors and warnings.

##### Currently
Project files have many pep8 errors and warnings.

##### Expected
Pep8 errors and warnings should be fixed

#### How should this be manually tested?
Install flake8 as part of the project's dependencies. 
Run flake8 command from the root directory.
No error or warning arises.

#### What are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/159356710

### CODE REVIEW

**Comment by 3V0L** [comment]
Good formatting @brandeddavid. The code is clear and easy to read now. I did notice that there is a test that was deleted  in the folder `wger/core/tests/test_delete_user.py`, can you please explain why?

**Comment by oagutu** [comment]
@brandeddavid good job fixing all the errors, definitely improves code readability. I do feel it would be necessary to have flake8 listed under 'requirements_devel.txt' since it would help future devs working on the project to maintain the flake8 style; what do you think?

**Comment by brandeddavid** [comment]
Thank you @3V0L and @oagutu for the reviews. That's a good suggestion @oagutu. Let me add it as part of the project's dependencies. @3V0L the reason I deleted the test was because it was a repetition. There was another test, in the same file that was testing the same functionality. It was raised as one of the errors by flake.

**Comment by ezrqnkemboi** [comment]
@brandeddavid I really like the work you have done. Keep it up.

**Pull request merged**
